#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    DO \$\$
    BEGIN
        CREATE USER $DATABASE_USER WITH PASSWORD '$DATABASE_PASSWORD';
        IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB') THEN
            CREATE DATABASE $POSTGRES_DB;
        END IF;
        GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DATABASE_USER;
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DATABASE_USER;
        ALTER DATABASE $POSTGRES_DB OWNER TO $DATABASE_USER;
    END
    \$\$;
EOSQL
