# Configuración base
line-length = 120
target-version = "py311"

# Configuración de formato
[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

# Configuración de linting
[lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "PL",  # pylint
    "RUF", # ruff-specific
]

# Ignorar reglas que entran en conflicto con black
ignore = ["E203", "E501"]

# Ignorar archivos específicos
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "build",
    "dist",
    "migrations",
    "venv",
    ".env",
    ".env.*",
]

# Configuración de reglas específicas
[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["S101"]

# Configuración de isort
[lint.isort]
known-first-party = ["app"]
