# Base configuration
line-length = 120
target-version = "py311"

# Format configuration
[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

# Linting configuration
[lint]
# Selected rules
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "PL",  # pylint
    "RUF", # ruff-specific
]

# Ignore rules that conflict with black
ignore = ["E203", "E501"]

# Ignore specific files
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "build",
    "dist",
    "migrations",
    "venv",
    ".env",
    ".env.*",
]

# File-specific rules
[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["S101"]

# isort configuration
[lint.isort]
known-first-party = ["app"]
