services:
  postgres:
    image: postgres:15-alpine
    container_name: task_db
    restart: always
    env_file:
      - secrets/secrets.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - task_network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    networks:
      - task_network

networks:
  task_network:
    name: task_network
    driver: bridge
    attachable: true
